export default {
  fontFamily: 'Arial, sans-serif',
  gradientStart: 'red',
  gradientMid: '#ab0c0c',
  gradientEnd: '#7c0505',
  locationFontColor: '#FFF',
  todayTempFontColor: '#FFF',
  todayDateFontColor: '#fff',
  todayRangeFontColor: '#fff',
  todayDescFontColor: '#fff',
  todayInfoFontColor: '#fff',
  todayIconColor: '#FFF',
  forecastBackgroundColor: '#FFF',
  forecastSeparatorColor: '#DDD',
  forecastDateColor: '#777',
  forecastDescColor: '#777',
  forecastRangeColor: '#777',
  forecastIconColor: 'red',
  containerDropShadow: '0px 3px 6px 0px rgba(50, 50, 50, 0.5)',
};
